# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_QCOM)	+= apq8016-sbc.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= apq8096-db820c.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= ipq8074-hk01.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= msm8916-mtp.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= msm8992-bullhead-rev-101.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= msm8994-angler-rev-101.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= msm8996-mtp.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= sdm845-mtp.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= i_qcom_Bengal_QRD.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= i_qcom_Bengal_SoC.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= i_qcom_generic.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= i_qcom_Scuba_2GB_DDR_SoC.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= i_qcom_Scuba_IDP.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= i_qcom_Scuba_IDP_USBC_Audio.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= i_qcom_Scuba_IOT_2GB_DDR_SoC.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= i_qcom_Scuba_IOT_IDP.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= i_qcom_Scuba_IOT_IDP_USBC_Audio.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= i_qcom_Scuba_IOT_QRD_NON_ELDO.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= i_qcom_Scuba_IOT_SoC.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= i_qcom_Scubap_IOT_SoC.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= i_qcom_Scubap_SoC.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= i_qcom_Scuba_QRD_ELDO.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= i_qcom_Scuba_QRD_IOT_ELDO.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= i_qcom_Scuba_QRD_NON_ELDO.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= i_qcom_Scuba_RUMI.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= i_qcom_Scuba_SoC.dtb


always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files    := *.dtb *.dtbo
